name: my-app

defaults:
  image: golang:1.25

tasks:
  - id: clone
    image: alpine/git:latest
    commands:
      - git clone --depth=1 $REPO_URL /workspace
      - cd /workspace && git checkout $COMMIT_SHA

  - id: build
    commands:
      - go build ./...
    depends_on: [clone]

  - id: test
    commands:
      - git config --global user.email "ci@example.com"
      - git config --global user.name "CI Bot"
      - go test $(go list ./... | grep -v 'pkg/integration/clients')
    depends_on: [clone]

integrations:
  linters:
    enabled: true
    tools:
      - name: golangci-lint
        image: golangci/golangci-lint:latest

triggers:
  pull_requests: true
  branches: [main,master]
